### ISSUE TITLE
Set-NodeInstallLocation error

### ISSUE THREAD

**Issue by mplawless** [aaronpowell/ps-nvmw#18]
Line 310 of the [nvm.psm1 file](https://github.com/aaronpowell/ps-nvmw/blob/master/nvm.psm1) is currently incorrect (commit 216ffca). Instead of:
`$settings = Get-Content $settings | ConvertFrom-Json`
it should be:
`$settings = Get-Content $settingsFile | ConvertFrom-Json`

Prolly easier for you to fix, than the overhead of a pull request.

**Comment by aaronpowell** [comment]
Pushed up a new release `1.5.0` which fixes this
