### ISSUE TITLE
Path to the msi file should be quoted.

### ISSUE THREAD

**Issue by nobiehl** [aaronpowell/ps-nvmw#19]
Ensure that you enclose the msi file path in double quotes in Install-NodeVersion. You'll get an error if there is a space in the directory name or filename.

**Comment by georgejean** [comment]
#20 fixes it (thanks for raising and solving this problem I've gone through today).
Anyway, as quoted in the nvm.psm1 file, the default installation path's folder (which often contains space(s)) should be redefined via `Set-NodeInstallLocation` to avoid problems due to too long filenames.

**Comment by aaronpowell** [comment]
@georgejean I'm not following, what's this issue?

**Comment by aaronpowell** [comment]
Closing old issue. If you believe this is still a problem reopen with steps to reproduce.

**Comment by georgejean** [comment]
@aaronpowell 
Sorry: I'm late. I just wanted to point out that your module also allows to redefine the installation path of
node.js to avoid spaces (and to avoid too long absolute paths, for example with `Set-NodeInstallLocation -Path C:\Temp` which is perhaps better than the `C:\Program Files\WindowsPowerShell\Modules` location).
