### ISSUE TITLE
Support .nvmrc

### ISSUE THREAD

**Issue by aaronpowell** [aaronpowell/ps-nvmw#2]
As per https://github.com/creationix/nvm/issues/110

**Comment by wrumsby** [comment]
e.g. if I have a `.nvmrc` in `~/somefolder/` that looks like this:

``` bash
v0.10
```

and then run:

``` bash
$ cd ~/somefolder
$ nvm install
$ nvm use
$ node -v
```

Running `nvm install` and `nvm use` will look at `./.nvmrc` and use that to determine the version of node to install and use.

**Comment by aaronpowell** [comment]
Cool, so how would you determine if you’re using io.js or node.js?

**Comment by wrumsby** [comment]
> Cool, so how would you determine if you’re using io.js or node.js?

AFAICT, a version number means a version of Node and `iojs` means "latest IO" (I guess?).

**Comment by aaronpowell** [comment]
So there'd be a prefix in the nvmrc?

I suppose this tool isn't really portable to OSX so compatibility is not _that_ important, just nice ;)

**Comment by wrumsby** [comment]
Supporting io.js seems like less of an issue now that the streams have been merged.

**Comment by aaronpowell** [comment]
That is true, probably need to look back at this :stuck_out_tongue:

**Comment by chaelli** [comment]
I changed the Set-NodeVersion function to read the .nvmrc files:

```
function Set-NodeVersion {
    param(
        [string]
        [Parameter(Mandatory=$false)]
        [ValidatePattern('^v\d\.\d{1,2}\.\d{1,2}$')]
        $Version
    )

    if ([string]::IsNullOrEmpty($Version)) {
        if (Test-Path .\.nvmrc) {
            $VersionToUse = Get-Content .\.nvmrc -Raw 
        }
        else {
            Write-Host "Version not given and no .nvmrc file found in folder"
            return
        }
    }
    else {
        $VersionToUse = $version
    }

    $VersionToUse = $VersionToUse.replace("`n","").replace("`r","")

    $requestedVersion = Join-Path $nvmwPath $VersionToUse

    if (!(Test-Path -Path $requestedVersion)) {
        Write-Host "Could not find node version $VersionToUse"
        return
    }

    $env:Path = "$requestedVersion;$env:Path"
    $env:NODE_PATH = "$requestedVersion;"
    npm config set prefix $requestedVersion
    $env:NODE_PATH += npm root -g
    Write-Host "Switched to node version $VersionToUse"
}
```

**Comment by aaronpowell** [comment]
Do you want to send a PR to merge (so you can get the credit too :wink:)?

**Comment by wrumsby** [comment]
This looks like it expects full version numbers (although my reading of the code might be off), e.g. `4.2.3` and while having _this_ would be a nice addition, the "standard" implementation of nvm supports "ranges", e.g. `4` will resolve to the latest version of 4, `4.2` to the latest of 4.2, etc.

That means _ideally_ the implementation would support those wildcards.

That said, I think that could be solved in a subsequent PR and I'd be keen to see even basic support provided.

\o/

**Comment by aaronpowell** [comment]
Cool - I personally don't use a nvmrc file so I'm happy to go with recommendations from those who do on how it should work.

When you say ranges, if you say `4` as the version in nvmrc will it use the latest _installed_ version, or latest _available_ version? I'd prefer the former, I don't want `Set-NodeVersion` to do installs too.

**Comment by wrumsby** [comment]
> When you say ranges, if you say 4 as the version in nvmrc will it use the latest _installed_ version, or latest _available_ version?

On OS X (and presumably other *nixes) it is the latest _available_.

From the command line:
- `nvm use 4` will use the latest _installed_ version
- `nvm install 4` will install the latest _available_ version and use that

If you have an `.nvmrc` file then `nvm use` and `nvm install` without a version number will use/install the version as per the file.

**Comment by aaronpowell** [comment]
Cool, seems useful. I'm curious how the "install latest available" works, but that's side tracking the discussion. If @chaelli doesn't send a PR in the next few days I'll just add it in myself :smile:

**Comment by aaronpowell** [comment]
Thanks @chaelli, merged in now. @wrumsby if you want to tackle the other features that it _could_ support I'm more than happy for PR's there too

**Comment by wrumsby** [comment]
>  I'm curious how the "install latest available" works, but that's side tracking the discussion.

`Get-NodeVersions` is pretty much the same thing as `nvm ls`.

nvm also supports `nvm ls-remote` which lists all the versions available to install, having something like that would make it possible to implement "install latest available".

**Comment by aaronpowell** [comment]
ah right. I'll have a dig into how nvm works, I'm not sure if there's any real "API" on Node.js that I can call to get the list (and my bash is a bit rusty so understanding nvm is a little slow :stuck_out_tongue: )

**Comment by aaronpowell** [comment]
And found it - https://nodejs.org/dist/index.json

**Comment by aaronpowell** [comment]
I've recently published v 1.0.2 to the PowerShell gallery (https://www.powershellgallery.com/packages/nvm/1.0.2) which now allows you to do wild-card version selection:

```
$> Set-NodeVersion v5
```

It'll then select the latest installed `v5` version of Node.js. This also works with `nvmrc` files.

I've also added a `-Remote` flag to `Get-NodeVersions` so you can see all versions of Node,js, and you can apply a filter:

```
$> Get-NodeVersions -Remote -Filter v5
```

That'll return all `v5.x` versions of Node.js.

**Comment by wrumsby** [comment]
\o/

**Comment by aaronpowell** [comment]
@wrumsby let me know if it works the way you expect it to work

**Comment by aaronpowell** [comment]
I think we can call this done
