### ISSUE TITLE
Error on macOS

### ISSUE THREAD

**Issue by felixfbecker** [aaronpowell/ps-nvmw#21]
I'm trying to use this on macOS, getting the following error:
```
> Install-NodeVersion latest
--2017-09-29 01:54:04--  https://nodejs.org/dist/latest/
Resolving nodejs.org... 104.20.23.46, 104.20.22.46, 2400:cb00:2048:1::6814:172e, ...
Connecting to nodejs.org|104.20.23.46|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’

index.html                                              [ <=>                                                                                                              ]   4.96K  --.-KB/s    in 0.003s

2017-09-29 01:54:04 (1.66 MB/s) - ‘index.html’ saved [5083]

Install-NodeVersion : The property 'content' cannot be found on this object. Verify that the property exists.
At line:1 char:1
+ Install-NodeVersion latest
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-NodeVersion], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Install-NodeVersion
```
is macOS supported?

**Comment by aaronpowell** [comment]
Admittedly I've never tried it on anything other than Windows. I don't have a mac available to test on, but let me crack out Docker and try a Linux version, there's probably chance of a similar problem.

How did you install it, from PowerShell Gallery or by cloning the repo?

**Comment by aaronpowell** [comment]
Just had a quick plan with it in a Docker container and it'll probably be a lot more of a challenge than initially thought.

So the problem that you're reporting above is caused by [this line](https://github.com/aaronpowell/ps-nvmw/blob/master/nvm.psm1#L139) where I use the `wget` alias for `Invoke-WebRequest` on Windows. Now that's a fairly easy problem to solve, but it then cascades into the next problem: https://github.com/aaronpowell/ps-nvmw/blob/master/nvm.psm1#L196

The function will download a MSI, which it then will unpack, which a) isn't possible `msiexec.exe` isn't available and b) the unpacked files wouldn't be of any use, they are Windows binaries 😛. I guess I could probably make it check the OS type (although I'm not sure how to do it in an xplat manner) and then download/unpack the right type as needed.

**Comment by felixfbecker** [comment]
I installed it with homebrew, but any PowerShell Code version should reproduce the issue. You probably should be able to just run PowerShell in WSL to reproduce it.

It would be fantastic if this version manager worked for any OS. The downloading/installation logic can probably be largely copied from how nvm does it.

Here's my version info if it helps:
```
>  $PSVersionTable                                                                                                      

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      6.0.0-beta                                                                              
PSEdition                      Core                                                                                    
GitCommitId                    v6.0.0-beta.7                                                                           
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-37...
Platform                       Unix                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
WSManStackVersion              3.0     
```

**Comment by aaronpowell** [comment]
**facemap*

Of course `$PSVersionTable` can tell me the OS in use! I might have a bit of a look into it, but I will need help doing the OSX testing as I don't have a device running that.

**Comment by felixfbecker** [comment]
Happy to test out any changes!

**Comment by felixfbecker** [comment]
Anything I can help out with? Any pointers?

**Comment by aaronpowell** [comment]
Shipped! https://www.powershellgallery.com/packages/nvm/1.5.1
