### ISSUE TITLE
Don't require v prefix / support semver

### ISSUE THREAD

**Issue by felixfbecker** [aaronpowell/ps-nvmw#23]
The bash nvm supports just running `nvm use 7` or `nvm install 7`, but ps-nvmw always requires `Set-NodeVersion v7` and `Install-NodeVersion v7.0.0`. It would be awesome to support something semver-like. Afaik PowerShell has a native `version` type that could be used

**Comment by aaronpowell** [comment]
Because there's also a `Install-NodeVersion latest` option it becomes a little more challenging as you can't use a `version` type for the parameter, it'd had to keep being a regex.

I'll admit to never having looked into the logic on how they do `install 7` because you'll need to find the latest release for that version.

**Comment by aaronpowell** [comment]
Just tried reading through the source of `nvm` to work out how that works and well... my `sh` skills are totally not good enough to work out how it's done 😛.

**Comment by felixfbecker** [comment]
I know, it's like reading Assembly! Contributing to the PowerShell version was so much easier 😄

**Comment by aaronpowell** [comment]
I just had a few minutes and was digging into the code again and realised something interesting about `Set-NodeVersion`.

Now that allows a level of fuzzy matching, you can do `Set-NodeVersion v8` which will then find the newest installed version of Node that matches `v8*` by internally using `Get-NodeVersions -Filter <pattern>` and taking the first match.

I could expand this to work also for `Install-NodeVersion` to run the following logic:

- If matches the regex -> install
- If no match on regex -> `Get-NodeVersions -Filter <pattern> -Remote | Install-NodeVersion`

Thoughts❓

**Comment by felixfbecker** [comment]
That would certainly be nice. It wouldn't fix the `v` prefix requirement of `Set-NodeVersion` and full semver support though

**Comment by aaronpowell** [comment]
Well it's really just like that because that's how it's represented in the node.js feed and so I don't have to append it myself 😉.

Making the `v` optional just means that the internals will need to do a bunch of checking.

**Comment by felixfbecker** [comment]
I don't understand, it already does fuzzy matching, so why can't that fuzzy matching work without `v`? Or just prepend the `v` at the top of the command if it's not there

**Comment by aaronpowell** [comment]
Oh it can, I was just being lazy when I wrote it originally!

**Comment by aaronpowell** [comment]
While working on the tests I've added this (since I can write tests to validate it 😛)

**Comment by aaronpowell** [comment]
Now supported in `1.6.0`!

**Comment by felixfbecker** [comment]
The validation regexp still requires the `v`:

```
Set-NodeVersion : Cannot validate argument on parameter 'Version'. The argument "7" does not match the "^v\d(\.\d{1,2}){0,2}$" pattern. Supply an argument that matches "^v\d(\.\d{1,2}){0,2}$" and try the command again.
At line:1 char:17
+ Set-NodeVersion 7
+                 ~
    + CategoryInfo          : InvalidData: (:) [Set-NodeVersion], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Set-NodeVersion
```

https://github.com/aaronpowell/ps-nvmw/blob/9784e5ada938a7485a6786371ac76b3ed78d37fb/nvm.psm1#L52-L53

**Comment by aaronpowell** [comment]
Ah whoops. Need to get test coverage on that and fix it with the regex I've got elsewhere.

**Comment by aaronpowell** [comment]
So we're calling this as done?
