### ISSUE TITLE
Persistent default on macOS

### ISSUE THREAD

**Issue by felixfbecker** [aaronpowell/ps-nvmw#24]
nvm allows to set the "default" version that persists after terminal, but the `-Persist` option in ps-nvmw currently doesn't seem to work on macOS (is that a bug in .NET core?).

Some options that make work:
- Add to `/etc/paths`
- Use `launchctl` to set a persistent `PATH`
- Add to `profile.ps1`

**Comment by aaronpowell** [comment]
I've thought it'd be better to move away from appending to `$env:PATH` and instead use the PowerShell profile so you're only setting in a PowerShell context, but that does admittedly make it a bit of a problem when you want a system-wide Node version (so that VS Code knows about it for example).

**Comment by felixfbecker** [comment]
Yeah I don't like the idea of having it only in PowerShell, that prevents a bunch of integration with e.g. tasks in vscode. And it should always be possible to have two shells side by side that run different node versions.

**Comment by aaronpowell** [comment]
If you don't use the `Persist` flag you can set the version for the current shell.

**Comment by elsassph** [comment]
Thanks a lot for making this module, and for making it mostly work on Mac :D

However it's a bit annoying/confusing to figure how to best set a default version.

I've gone with calling `Set-NodeVersion <my default>` in my pwsh profile, and if that's the recommended way to go, then it would be nice to add a note in the readme for Linux/Mac users.

PS: also the main documentation doesn't indicate that `-Persist` only works on Windows.

**Comment by aaronpowell** [comment]
The fact that it doesn't persist on MacOS is a bug, but I don't have access to a Mac to try and resolve it. If someone wants to jump in and try and fix that I'm accepting of PR's!

**Comment by elsassph** [comment]
Ok @aaronpowell, I've had a look.

Generally when `nvm-sh` installs, it edits the profile script to execute itself. When executing itself it redefines the path.

I guess that's the approach.

**Comment by felixfbecker** [comment]
I currently simply run `Set-NodeVersion` in my profile.ps1, or in my `prompt` function to read the current dirs package.json.

**Comment by elsassph** [comment]
PR done: default version is persisted and a call to `Set-NodeVersion` is added to the profile script.
