### ISSUE TITLE
Rename to ps-nvm?

### ISSUE THREAD

**Issue by felixfbecker** [aaronpowell/ps-nvmw#25]
Now that it's not Windows-specific anymore, what about renaming the repo? GitHub sets up redirects and the module is just called `nvm`

**Comment by aaronpowell** [comment]
The reason the module is called just `nvm` was because it was originally `NodeVersionManager` but I was hitting too many long-path issues on Windows 😛.

I'm happy to rename the repo to just drop the `w`, but I'd like to keep something in the name that indicates it's PowerShell centric.

**Comment by felixfbecker** [comment]
Should definitely wear the ps prefix with pride!

**Comment by aaronpowell** [comment]
Done, dropped the `w`

**Comment by felixfbecker** [comment]
@aaronpowell I think you need to re-configure AppVeyor

**Comment by aaronpowell** [comment]
Oh yeah, the services probably don't get the redirects

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by felixfbecker** [comment]
Let me know when you did so I can build #39

**Comment by aaronpowell** [comment]
I've created a new AppVeyor item against `ps-nvm`. I don't think Travis or CodeCov needs anything to be done.
