### ISSUE TITLE
In addition to .nvmrc, read engines field from package.json

### ISSUE THREAD

**Issue by felixfbecker** [aaronpowell/ps-nvmw#26]
Since it's trivial in PowerShell to parse JSON it would be so awesome if I could just run `Set-NodeVersion` on any cloned open source repo and it directly uses the needed version as declared in package.json. A lot of packages have the engines field specified but only few have a .nvmrc

**Comment by aaronpowell** [comment]
Do people actually use that part of the `package.json`? I'll admit to having almost never set it 😛.

But yeah, it could be a fallback.

**Comment by felixfbecker** [comment]
Totally!

https://github.com/expressjs/express/blob/351396f971280ab79faddcf9782ea50f4e88358d/package.json#L82

 https://github.com/sequelize/sequelize/blob/34d075e2a5575108a037debcd66e814fd6dd5c4c/package.json#L141

It's what powers these little awesome badges in READMEs, super useful:

![node](https://img.shields.io/node/v/sequelize.svg)

**Comment by aaronpowell** [comment]
Today's pretty hectic for me so I probably can't get to it, but I won't say no to a PR!

**Comment by felixfbecker** [comment]
It would depend on #23 because the versions in there are semver ranges.

**Comment by aaronpowell** [comment]
I don't think the `version` type supports ranges, so might be regex still!

**Comment by felixfbecker** [comment]
@aaronpowell semver ranges are not a regular grammar unfortunately. Can PowerShell modules have NuGet dependencies? https://github.com/adamreeve/semver.net

**Comment by aaronpowell** [comment]
.... kind of.

Publishing to the gallery is really quite simplistic, it just scans the directory you're publishing and creates a NuGet package that contains every file and pushes that up to the gallery.

So if you install the contents of that NuGet package into the folder it'll be included (it's how one of the releases shipped with a bunch of node releases by accident!).

Just thinking through the practicalities of it - you'd need to parse the range from out of the `package.json`, then download all the known versions and find out which one matches. I'm concerned about the overall performance of it, could result in a lot of calls to Node.js's website.

**Comment by felixfbecker** [comment]
Got it. I don't think requesting https://nodejs.org/dist/index.json before the install to figure out the best version would be a big deal, compared to the download itself.
Would it be a better approach to have PowerShell cmdlets for semver.net and define that as a dependency?

**Comment by aaronpowell** [comment]
I'm wondering if it wouldn't be smarter to wrap all the version detection logic up into a .NET library, then you could add the stuff for #23 as well.

**Comment by aaronpowell** [comment]
How about I convert you into a full contributor so you can work on this without relying on a fork?

**Comment by felixfbecker** [comment]
Sounds good!

**Comment by aaronpowell** [comment]
So we're calling this as done?

**Comment by felixfbecker** [comment]
Yup
