### ISSUE TITLE
CI and tests

### ISSUE THREAD

**Issue by felixfbecker** [aaronpowell/ps-nvmw#27]
It would be nice to test this in CI on AppVeyor for Windows and Travis for macOS.

Example: https://github.com/dahlbyk/posh-git

**Comment by felixfbecker** [comment]
Actually looks like VSTS is enabled but fails on every commit and not visible publicly?

**Comment by aaronpowell** [comment]
[Here's why it's on VSTS](https://www.aaron-powell.com/posts/2016-02-08-deploying-powershell-modules-with-vsts-build/), no reason other than I wanted to blog about it.

That said, since the blog was written some stuff changed with the agents and now the build fails, but given that the commits come in so infrequently doing a manual release was not a bother for me.

For testing - I _once_ looked at Pester but it was only a fairly superficial look at it and I decided that it was well down my priority list for this module and I moved on to other problems to solve.

More than happy to have it done, it's just a low priority for **me** to do 😉

**Comment by felixfbecker** [comment]
So there isn't anything special really about VSTS and the deploy could happen from Travis or AppVeyor as well? I have used VSTS for private things but even after googling could not find any documentation on how to configure it to properly run on PRs and report status checks, make all build logs public, configurable through a commited config file etc. Seems like it is not that suited for open source - even https://github.com/Microsoft/vscode deploys with VSTS, but runs public builds on Travis and AppVeyor.

When you say "manual release" does that mean VSTS deployed a new version on every commit like https://github.com/semantic-release/semantic-release does? Or by pressing a button in VSTS?
I would be happy to get semantic-release set up, that would be awesome. I am just not sure at all what commands it has to run at all to publish, but now that you've linked me your blog post I guess that should be possible to replicate in a different CI provider.

**Comment by aaronpowell** [comment]
I've got no issue using AppVeyor or Travis if there's tests to be run, but right now it doesn't really provide any value, VSTS is just for Release, which doesn't work anyway. And I don't mind doing the merge to `master` and push to PS Gallery, it's not a big overhead.

FWIW - the reason that VSTS doesn't work is that the VSTS agents don't have the latest version of PowerShell to be able to deploy to the gallery (and I've been too lazy to fix it)

**Comment by aaronpowell** [comment]
Woo, there we go, PR open with some tests!

I have no idea how to get it working on Travis or Circle though...

**Comment by felixfbecker** [comment]
Nice! I had some tests written too but couldn't get the TestDrive / mock file system to work on macOS, Pester is still working on compatibility. We can get it to run on AppVeyor though.

**Comment by aaronpowell** [comment]
`TestDrive` only kind of works on Windows, it drops things into your temp folder, which means that you blow out the file path when unpacking with msiexec :(

**Comment by felixfbecker** [comment]
Oh, okay. Then it's probably better for us to use the temp folder ourselves. But there probably is a way to get the temp folder in a platform-independent way

**Comment by aaronpowell** [comment]
`$env:TEMP` will return you the temp folder location, and that's what `TestDrive` uses internally. The problem becomes on Windows is that that lives in `%appdata%`, which is like `C:\Users\<username>\AppData\Local\Temp`, and when a GUID is popped on there we're already close to the 256 character issue.

You could try and push it somewhere else, but then you need to ensure that you've got write access to it (eg: `C:\tmp` or `/tmp`) which in a build environment isn't something I'd want to rely on.

Fun fact - the long file issue is the reason I wrote the `Set-NodeInstalLocation` feature anyway 😛.

**Comment by aaronpowell** [comment]
If you've written some tests that complement the ones I have in the PR feel free to add them

**Comment by aaronpowell** [comment]
So, we can mark this as Closed now?

**Comment by felixfbecker** [comment]
Can the failing VSTS commit status check go away?

**Comment by aaronpowell** [comment]
Done
