### ISSUE TITLE
processor architecture option

### ISSUE THREAD

**Issue by adicirstei** [aaronpowell/ps-nvmw#3]
Hi,

I am in the process to switch to powershell and setting up my environment. Here's the thing. I would like to be able to choose whether to install 32bit version or 64bit. Currently the function uses `PROCESSOR_ARCHITECTURE` to decide.

How about letting user to decide? Currently you have this code:

``` powershell
    if ($env:PROCESSOR_ARCHITECTURE -eq 'AMD64') {
        $msiFile = "node-$version-x64.msi"
        $nodeUrl = "http://nodejs.org/dist/$version/x64/$msiFile"
    }
```

I see two options: either include it in version parameter like `v0.12.2-x64` either adding a new optional parameter.
Thanks!

**Comment by aaronpowell** [comment]
I've recently added this. It won't unpack into different folders based on architecture so you can't install the same Node version with different architectures, but that (hopefully) isn't a common use case.
