### ISSUE TITLE
File name too long error

### ISSUE THREAD

**Issue by liberalGeorge** [aaronpowell/ps-nvmw#4]
Hi 

When I try to install Node v0.12.7 I get an error regarding the file path name length. This happens after Node has downloaded and the installer starts running, early during the configuration stage.

I've tried forcing the nvm module to install closer to my disc root, but when I run Install-NodeVersion v0.12.7 it saves to disc in $home\Documents\WindowsPowerShell\Modules. 

lG

**Comment by airtonix** [comment]
Same problem here.

**Comment by gamicklisafisherr** [comment]
The reason of this error message is windows has this limitation and some of the utility like Long Path Tool can handle this issue. I have gone through various forums and found this is the generic problem and most of them suggested this tool.

**Comment by aaronpowell** [comment]
Unfortunately this is a problem with Windows file system pathing and Node.js (well npm specifically). Windows has a max file path length of 260 characters which is often exceeded by npm and its modules. The only solution is to use an alternate path for the module to be installed into.
