### ISSUE TITLE
Setup VSTS release process

### ISSUE THREAD

**Issue by aaronpowell** [aaronpowell/ps-nvmw#46]
I want to be able to release new builds easily, VSTS can do that for me, but I need to get it setup properly.

**Comment by felixfbecker** [comment]
Why not release from Travis or AppVeyor?

**Comment by aaronpowell** [comment]
I'm using the `Release` feature of VSTS, as the process is:

- Every `master` build is a potential release
- A release has to be approved before it pushed to the gallery

It's basically what I had before but I added another step so that a master merge must be approved as a release rather than auto released.

**Comment by felixfbecker** [comment]
I don't really understand the point of that approval flow, that sounds useful for a big software product, but for a small open source module? I don't like that VSTS is completely closed to the public, noone can see the logs or know what revisions have approved releases etc. Even clicking on the (public) VSTS status checks just gives a 401.
I think the same functionality can be easily achieved with just git and public CI, e.g. by releasing on every pushed tag, or always releasing master and having a `next` development branch.

**Comment by aaronpowell** [comment]
I don't think there's a need to have the release process open to the public. There shouldn't be any links to VSTS popping up in PR's or such (if so, I need to fix that).

There are ways which it can be done with a bunch of other services but it's already up and running and I don't *really* want much more time invested in the CI/CD process, it's already pretty extensive for a single PowerShell module 😛
