### ISSUE TITLE
Overhaul README

### ISSUE THREAD

**Issue by felixfbecker** [aaronpowell/ps-nvmw#51]
With all the new features the README got out of date.

**Comment by felixfbecker** [comment]
@aaronpowell hacked together a small documentation generator in https://github.com/aaronpowell/ps-nvm/tree/docs

**Comment by felixfbecker** [comment]
This dumps the command reference into the readme, which feels very bloated to me. Most commands are never needed. I think in the readme we should provide no reference at all and only a "getting started" guide that shows how install the module, install and set a node version. Then we can link to the docs, preferably hosted so we don't need to maintain generated files in source control. Wdyt?

**Comment by aaronpowell** [comment]
Why not push each cmdlet into a separate file under a `docs` folder? That way they can be deep linked using https://msdn.microsoft.com/en-us/library/hh852737(v=vs.85).aspx.

And what happened to my build matrix table 😝.

**Comment by felixfbecker** [comment]
It... had to go 😅  I felt it was bloating the top of the readme a lot, the top should only have quick statuses of the health of the project and a short description.

I already added deeplinking 😉 
https://github.com/aaronpowell/ps-nvm/blob/96838f4c83a90fa3d7a473163e46072a0c7fec38/nvm.psm1#L54-L55

**Comment by aaronpowell** [comment]
Want to open this as a PR so it can get into 2.0?
