### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by ducksoupdev** [aaronpowell/ps-nvmw#6]
Hi, I have created a chocolatey package for ps-nvmw to make it easy to install.

https://github.com/ducksoupdev/ps-nvmw-choco

The plan is to submit it to the chocolatey site, hope that's ok with you?

**Comment by aaronpowell** [comment]
If you want to manage it via Chocolatey it's all yours, my recommendation will be to install it from [PowerShell Gallery](https://www.powershellgallery.com/packages/nvm).
