### ISSUE TITLE
msi install fails silently on Windows

### ISSUE THREAD

**Issue by stacy-andrews** [aaronpowell/ps-nvmw#65]
Trying to run 

`Install-NodeVersion 8`

Will fail silently with a path too long error.

Looking at my node install location with

`Get-NodeInstallLocation`

I get 

> C:\Users\IEUser\Documents\WindowsPowerShell\Modules\nvm\2.0.2\vs

I think this is because I installed ps-nvm with this command:

`Install-Module nvm -Scope CurrentUser`

Please note, I intend on sending a PR, but wanted to raise the issue first.

**Comment by stacy-andrews** [comment]
My workaround is to update the Node Install Location to something simpler, like 

> c:\node_installs

With

`set-nodeinstalllocation c:\node_installs`

**Comment by aaronpowell** [comment]
Hmm I'm surprised it fails silently, it should tell you that you've hit a path length issues.

That's exactly why I have the `Set-NodeInstallLocation` cmdlet, I can't find any better way to solve it.

**Comment by ztolley** [comment]
Same here

**Comment by aaronpowell** [comment]
Unfortunately, there's not a whole lot I can do to rectify this, it's a limitation of `msiexec` and how it handles long paths.

**Comment by aaronpowell** [comment]
Closing as this is something beyond my ability to resolve.
