### ISSUE TITLE
Install-NodeVersion doesn't work without version number

### ISSUE THREAD

**Issue by roelfjan** [aaronpowell/ps-nvmw#67]
I want to get my node version from the `.nvmrc` file. According to the README, this should be possible:
```
# Install the Node version specified in .nvmrc or package.json engine field
Install-NodeVersion
```

This gives (on AppVeyor) this error:
```
Install-NodeVersion : Cannot process command because of one or more missing mandatory parameters: Version.
At line:1 char:1
+ Install-NodeVersion
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-NodeVersion], ParameterBindingException
    + FullyQualifiedErrorId : MissingMandatoryParameter,Install-NodeVersion
 
Command executed with exception: Cannot process command because of one or more missing mandatory parameters: Version.
```

Which is correct if I look at https://github.com/aaronpowell/ps-nvm/blob/master/nvm.psm1#L161, because the `$Version` param is mandatory.

The question is: is this is bug in the source code or in the README? 
Btw: for now I use `Install-NodeVersion (Get-Content ./.nvmrc -Raw)`, which works as well.

**Comment by aaronpowell** [comment]
Ah that's actually a bug in the documentation, it will _set_ based on the `.nvmrc` but not install (that logic has never been written).

I can easily fix the doco to remove that, but maybe I should make it work that way instead...

**Comment by bjornhanson** [comment]
I'm working on something where I need the version to be installed based on whatever is in `.nvmrc`. It'd be great if you added that functionality.

**Comment by aaronpowell** [comment]
We do support nvmrc https://github.com/aaronpowell/ps-nvm/blob/master/nvm.tests.ps1 has tests covering it

**Comment by rvdginste** [comment]
@aaronpowell It would be nice if it would work as mentioned in the documentation.

I bumped into this because I executed "Set-NodeVersion" in a project that has a ".nvmrc". This executed just fine, but changed my path to point to a node version I did not have installed. (An error might be better in that case?) Currently there's no easy way to install the required version: one has to manually take the version from the ".nvmrc" and use it with "install-nodeversion".

See pull request #76

**Comment by aaronpowell** [comment]
Fixed with #76, thanks @rvdginste. 😁 

Rolling out in release 2.4.0

**Comment by jacobrillema** [comment]
@aaronpowell When is this getting rolled out? I was under the impression this worked out of the box on the current version.

**Comment by aaronpowell** [comment]
Should've rolled out when I merged and released. Let me check the pipeline

**Comment by aaronpowell** [comment]
Looks like Azure Pipelines killed the agent before it released. I'll have to do into it

**Comment by aaronpowell** [comment]
And it seems the underlying issue is an error thrown when publishing to the gallery. *sigh* And I thought this would be easy

**Comment by aaronpowell** [comment]
Ok, deployed!
