### ISSUE TITLE
npm prefix not set

### ISSUE THREAD

**Issue by aaronpowell** [aaronpowell/ps-nvmw#70]
When you set a node version the [`npm prefix`](https://docs.npmjs.com/cli/prefix) should be relative to the node version you're using.

I think we can just get away with setting `$NPM_CONFIG_GLOBALCONFIG` and creating a custom `.npmrc` file that is in the current node version folder.

**Comment by k-j-kleist** [comment]
Good thinking. From my PowerShell profile:

```
# after installing a newer version of node.js, do the following once...
#
#     npm config set prefix 'C:\n\npm\vX.Y.Z'
#     npm config set cache 'C:\n\npm-cache\vX.Y.Z'
#
# ... using the output from these two commands:
#
#   Get-NodeInstallLocation
#   node --version
```

**Comment by aaronpowell** [comment]
Yeah I just noticed it as I'm setting up a new machine and realised it wasn't working 😝
