### ISSUE TITLE
[nvm version 2.1.0] "Remove-NodeVersion -version 10.1.0" fails due to incorrect regexp

### ISSUE THREAD

**Issue by k-j-kleist** [aaronpowell/ps-nvmw#71]
C:\tmp> remove-nodeversion -version v10.1.0
Remove-NodeVersion : Cannot validate argument on parameter 'Version'. The argument "v10.1.0" does not match the "^v\d\.\d{1,2}\.\d{1,2}$" pattern.

The current pattern assumes that the major version is 9 at the most.

Aside: the example in the docs `Remove-NodeVersion v5.0.0` lacks `-Version`

**Comment by aaronpowell** [comment]
Haha nice catch, we're only matching a single digit on the major version!

**Comment by aaronpowell** [comment]
Should be all working in the [`2.1.1` release](https://www.powershellgallery.com/packages/nvm/2.1.1)
