### ISSUE TITLE
Cannot switch to lower version number

### ISSUE THREAD

**Issue by felixfbecker** [aaronpowell/ps-nvmw#78]
`Set-NodeVersion` doesn't properly _replace_ the version in PATH as it should, it always _prepends_ it. However, when the same version is then already in the PATH, but shadowed by another version, it doesn't do anything. This makes it impossible to switch to a lower version number after `Set-NodeVersion` set a higher one, e.g. if you have `Set-NodeVersion` in your `prompt()` function to always apply the package.json `engines.node` field.

To reproduce:

```powershell
> Set-NodeVersion 11
> $env:PATH -split ':' | select-string nvm
/usr/local/share/powershell/Modules/nvm/2.3.0/vs/v11.15.0/bin

# This should *replace* the entry, but instead it *prepends*:
> Set-NodeVersion 12
> $env:PATH -split ':' | select-string nvm
/usr/local/share/powershell/Modules/nvm/2.3.0/vs/v12.2.0/bin
/usr/local/share/powershell/Modules/nvm/2.3.0/vs/v11.15.0/bin

# This should *replace* the entry too, but instead it does nothing and v12 stays active:
> Set-NodeVersion 11
> $env:PATH -split ':' | select-string nvm
/usr/local/share/powershell/Modules/nvm/2.3.0/vs/v12.2.0/bin
/usr/local/share/powershell/Modules/nvm/2.3.0/vs/v11.15.0/bin
```

**Comment by aaronpowell** [comment]
Weird, let's get a test in for that and fix it
