### ISSUE TITLE
Feature Request: Get-NodeVersion

### ISSUE THREAD

**Issue by eedwards-sk** [aaronpowell/ps-nvmw#81]
I would like to be able to query the current `Set-NodeVersion` by using a command called `Get-NodeVersion` that would return the current version being used.

This would be similar to how e.g. `pyenv` allows you to type `pyenv version-name` and get the name of the current pyenv.

I could use this for decorating my prompt, for example.

**Comment by aaronpowell** [comment]
Is there a reason you couldn't just use `node -v`?

If there was to be a commandlet added I'd expect that's all it does as the module doesn't actually track what the currently set Node version is.

**Comment by eedwards-sk** [comment]
> the module doesn't actually track what the currently set Node version is.

Ah, maybe that's the information that I was missing. I was expecting that if there was a `Set-NodeVersion` command, there was some state maintained somewhere. I guess I need to further look into how it's changing the current version.

**Comment by eedwards-sk** [comment]
`node -v` seems to work as a workaround for now, closing.
